{
  #inputs,
  #config,
  #lib,
  pkgs,
  ...
}:

{
  programs = {
    #bash
    bash = {
      enable = true;
      initExtra = ''
        #eval "$(pay-respects bash)"

      '';
    };

    #fish
    fish = {
      enable = true;
      package = pkgs.fish;
      /*
        shellAliases = {
          rm = "echo Use 'rip' instead of rm." ;
          rip = "rip --graveyard ~/.local/share/Trash" ;
        };
      */
      interactiveShellInit = ''

      '';
      #try shellInit if below option isn't your preference
      shellInitLast = ''
        #pay-respects fish | source
      '';
    };

    #nushell
    nushell = {
      enable = true;
      package = pkgs.nushell;
      plugins = with pkgs.nushellPlugins; [
        gstat
        #net
        #hcl
        #skim
        #query
        highlight

      ];
      settings = {
        #show_banner = false;
        highlight_resolved_externals = true;
        completions.external = {
          enable = true;
          max_results = 200;
        };
        history = {
          max_size = 10000;
        };
        color_config = {
          shape_external = "red"; # color of unresolved externals (see 'ansi --list')
          shape_external_resolved = "white"; # color of resolved externals
        };
        cursor_shape.emacs = "line";
        # better use explore instead instead if below gimmick for pager
        #hooks.display_output = "table -e --width 1000 | less -FSRX";
        #hooks.display_output = "table -e --width 1000 | less -FSR";
        #hooks.display_output = "table -e --width 1000 | less -FS";
        #hooks.display_output = "table -e --width 1000 | less -SRX";
        #hooks.display_output = "table -e --width 1000";
      };

      extraConfig = ''
        $env.config.hooks.command_not_found = [
          {|cmd| ^command-not-found $cmd | print }  
        ]

        #pay-respects nushell
        
      '';
      /*
        # Add your shell init command here
          $env.config.hooks.pre_prompt = [
            {||
              #some commanda here
            }
          ]
        '';
      */
      extraEnv = ''
        # dummy line added just for sake of immutable symlink file generated by nix
        # so that we can't change behaviour through imperative methods
      '';

    };

  };
  home.shell.enableNushellIntegration = true;

}
